name: Lab4ManualLayout
options:
  minimumXcodeGenVersion: 2.38.0
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
    SWIFT_VERSION: 5.0
    PRODUCT_BUNDLE_IDENTIFIER: com.pavel.lab4manuallayout
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
targets:
  Lab4ManualLayout:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: ViewControllers
